spring:
   profiles:
      active: -dev

---
spring: 
   profiles: dev  #开发环境
   application:
       name: microservicecloud-config-dev
server:
   port: 8001

---
spring: 
   profiles: test  #测试环境
   application:
       name: microservicecloud-config-test
server:
   port: 8002
