spring:
   profiles:
   active: -dev

---
spring:
   profiles: dev
   application: 
      name: microservicecloud-config-client
server:
  port: 7001
  
eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7002:7002/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000

---
spring:
   profiles: test
   application: 
      name: microservicecloud-config-client
server:
    port: 8202
eureka:
   client:
      service-url:
         defaultZone: http://eureka-test:7001/eureka/
